Adding `cc!notes @user` command
CodecademyCommunity/codecademy-discord-bot pull request #111
Opened 2021-03-15 01:50 UTC by fedGL

## What issue is this solving?
Closes #41 and continues push for issue #7 

### Description
Fourth and final command from the infractions and notes family of commands. This is a refactoring of the very functionally-similar `cc!infractions @user` command. It should work out the box.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? No
- Any new dependencies to install? No
- Any special requirements to test? Admin/Mod/SU
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

2021-03-16 06:01 UTC, aedwardg requested changes
Great job @fedGL!  

Just two tiny changes and two comments about potential future restructuring (for separate issues/PRs).

2021-03-20 11:19 UTC, fedGL commented on commands/moderation/notes.js
> +    if (targetUser) console.log(`targerUser is true`);
Done, `console.log` removed

2021-03-20 11:20 UTC, fedGL commented on commands/moderation/notes.js
> +      notesLog(msg, targetUser, result);
Check 👍

2021-03-20 11:20 UTC, fedGL commented on commands/moderation/notes.js
> +  });
Noted 👍 We can create a new issue to refactor reused coded into another place

2021-03-20 11:21 UTC, fedGL commented on commands/moderation/notes.js
> +    'what? You want ALL the notes from everyone? You forgot the targer user',
Fixed

2021-03-20 13:33 UTC, aedwardg approved these changes
LGTM! 🚀

2021-03-22 04:41 UTC, Vic-ST approved these changes
LGTM!

2021-03-22 04:41 UTC, merged