Allow mods to ban+unban, remove archived from docs
CodecademyCommunity/codecademy-discord-bot pull request #157
Opened 2021-05-08 18:28 UTC by Victoria-DR

## What issue is this solving?

Closes #155 

### Description

- Allow mods to ban and unban users.
- Remove the four archived Discourse-related commands from cc!help and README.

## Any helpful knowledge/context for the reviewer?

- Is a re-seeding of the database necessary? NO
- Any new dependencies to install? NO
- Any special requirements to test? Moderator role.
  - (e.g., admin perms, alt account, etc.)

### Please make sure you've attempted to meet the following coding standards
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2021-05-08 21:47 UTC, Vic-ST approved these changes
LGTM!

2021-05-10 16:04 UTC, aedwardg requested changes
@Victoria-DR, 

A couple of tiny changes and then this will be ready to go.

2021-05-10 16:04 UTC, aedwardg commented on commands/utility/help.js
> +        .addField('Admin Only', 'cc!ban, cc!unban, cc!clearinfractions')
Ban and unban shouldn't be listed as Admin-only anymore after this change.

2021-05-12 18:52 UTC, aedwardg approved these changes
Thanks @Victoria-DR,

This looks ready to go.

2021-05-13 17:16 UTC, merged