filter update
CodecademyCommunity/codecademy-discord-bot pull request #159
Opened 2021-05-09 00:01 UTC by Shaylin-TRK

## What issue is this solving?

Closes #158 

### Description

Added the ability to treat '0' as an 'o' so that spellings such as 'g0damn' are not missed.

- Is a re-seeding of the database necessary? NO
- Any new dependencies to install? NO
- Any special requirements to test?
  Can't have SU, Mod, or Admin for the filter to check your messages

### Please make sure you've attempted to meet the following coding standards
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2021-05-09 01:01 UTC, Victoria-DR reviewed
Looks good, just would like to request a few additional changes regarding the issues below.

- The filter only works for words that are completely lowercase.
- `3` could be used as a substitute for `E` or `e`. Maybe [this](https://www.netlingo.com/word/leetspeak.php) could be useful?

2021-05-09 01:24 UTC, Shaylin-TRK commented
Thanks @Victoria-DR! Fixed!

2021-05-09 17:42 UTC, Victoria-DR approved these changes
Looks great, thanks!

2021-05-10 02:50 UTC, Vic-ST requested changes
Hey, could you fix the "who're" being caught as whore?

2021-05-16 22:21 UTC, Shaylin-TRK commented
Should be fixed now!

2021-05-17 19:46 UTC, Vic-ST approved these changes
LGTM! Thanks for the work you did on this!

2021-05-18 17:56 UTC, aedwardg approved these changes
Good work as always, @Shaylin-TRK 

I still think we should move to using the bad-words library, but this is okay in the meantime.
The main thing is that pushing this change will keep people's messages from deleting even if the bot thinks there's some serious profanity.

2021-05-18 17:58 UTC, merged